"use client";
import Image from "next/image";
import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
// Removed unused UI imports for a cleaner page
import PinnedCountdownDesktop from "../../components/PinnedCountdownDesktop";
import { track } from "../../lib/ga4";

// Generate arrays of review image paths (use only reviews2 on this page)
const namedReviewBases = [
  "Allen", "Andrea", "Cristina", "Daniela", "DanielR",
  "Deja", "Hani", "Jackie", "Kenneth", "Kia",
  "Latrell", "lauren", "Madeline", "Marlaren", "Martiza",
  "Meghan", "Nathan", "Nikolas", "Rachel", "Trey"
];
// Reorder so: row 2 = Trey, lauren, Martiza; row 3 = Rachel, Marlaren, Meghan
const secondRowTargets = ["Trey", "lauren", "Martiza", "Maritza"]; // include variant spelling
const thirdRowTargets = ["Rachel", "Marlaren", "Meghan"];
const exists = (name: string) => namedReviewBases.includes(name);
const row2 = secondRowTargets.filter(exists);
const row3 = thirdRowTargets.filter(exists);
const others = namedReviewBases.filter(n => !row2.includes(n) && !row3.includes(n));
const firstRow = others.slice(0, 3);
const remaining = others.slice(3);
const orderedNames = [...firstRow, ...row2, ...row3, ...remaining];
// Prefer WebP versions (generated by scripts/convert-webp.mjs). Next/Image will handle fallbacks if needed.
const namedReviews = orderedNames.map(base => `/Gallery/reviews2/${base}.webp`);
const allReviews: { src: string }[] = namedReviews.map(src => ({ src }));

const columnCountFromWidth = (width: number): number => {
  if (width >= 1536) return 6;
  if (width >= 1280) return 5;
  if (width >= 1024) return 4;
  if (width >= 768) return 4;
  if (width >= 640) return 3;
  return 2;
};

const arraysMatch = (a: number[], b: number[]) =>
  a.length === b.length && a.every((val, idx) => val === b[idx]);

export default function ReviewsPage() {
  const [countdown, setCountdown] = useState(10);
  const [done, setDone] = useState(false);
  const router = useRouter();
  const [activeReviewIndices, setActiveReviewIndices] = useState<number[]>([]);
  const [columnCount, setColumnCount] = useState<number>(2);
  const spotlightEnabled = columnCount >= 3;
  const reviewRefs = useRef<(HTMLDivElement | null)[]>([]);
  const rowGroupsRef = useRef<number[][]>([]);
  const observerRef = useRef<IntersectionObserver | null>(null);
  const totalReviews = allReviews.length;
  const rowGroups = useMemo(() => {
    const groups: number[][] = [];
    for (let i = 0; i < totalReviews; i += columnCount) {
      const row: number[] = [];
      for (let j = 0; j < columnCount && i + j < totalReviews; j += 1) {
        row.push(i + j);
      }
      groups.push(row);
    }
    return groups;
  }, [columnCount, totalReviews]);

  // Helper function to check if current time is between 7am-7pm EST
  const checkBusinessHours = () => {
    const now = new Date();
    // Convert to EST/EDT (America/New_York timezone)
    const estTime = new Date(now.toLocaleString('en-US', { timeZone: 'America/New_York' }));
    const hour = estTime.getHours();
    return hour >= 7 && hour < 19; // 7am to 7pm EST
  };

  // Time-based message state - initialize with correct value
  const [isBusinessHours, setIsBusinessHours] = useState(() => checkBusinessHours());

  // Re-check business hours every minute
  useEffect(() => {
    const interval = setInterval(() => {
      setIsBusinessHours(checkBusinessHours());
    }, 60000); // Check every minute
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    if (done) return;
    if (countdown <= 0) {
      setDone(true);
      return;
    }
    const id = setTimeout(() => setCountdown(v => v - 1), 1000);
    return () => clearTimeout(id);
  }, [countdown, done]);

  useEffect(() => {
    if (typeof window === "undefined") return;
    const mq = window.matchMedia("(min-width: 768px)");
    setSpotlightEnabled(mq.matches);

    const handleChange = (event: MediaQueryListEvent) => {
      setSpotlightEnabled(event.matches);
    };

    if (typeof mq.addEventListener === "function") {
      mq.addEventListener("change", handleChange);
    } else {
      mq.addListener(handleChange);
    }

    return () => {
      if (typeof mq.removeEventListener === "function") {
        mq.removeEventListener("change", handleChange);
      } else {
        mq.removeListener(handleChange);
      }
    };
  }, []);

  useEffect(() => {
    if (typeof window === "undefined") return;
    const updateColumns = () => setColumnCount(columnCountFromWidth(window.innerWidth));
    updateColumns();
    window.addEventListener("resize", updateColumns);
    return () => window.removeEventListener("resize", updateColumns);
  }, []);

  useEffect(() => {
    rowGroupsRef.current = rowGroups;
  }, [rowGroups]);

  useEffect(() => {
    if (!spotlightEnabled) {
      setActiveReviewIndices([]);
      if (observerRef.current) {
        observerRef.current.disconnect();
        observerRef.current = null;
      }
      return;
    }

    if (typeof window === "undefined") return;

    const observer = new IntersectionObserver(
      entries => {
        let bestRowIndex: number | null = null;
        let bestScore = -Infinity;

        entries.forEach(entry => {
          if (!entry.isIntersecting) return;
          const target = entry.target as HTMLElement;
          const rowAttr = target.dataset.rowIndex;
          if (rowAttr == null) return;

          const row = Number(rowAttr);
          const ratio = entry.intersectionRatio;
          const offset = entry.boundingClientRect.top / Math.max(window.innerHeight, 1);
          const score = ratio - offset * 0.4; // prioritize nearer to top while considering visibility

          if (score > bestScore) {
            bestScore = score;
            bestRowIndex = row;
          }
        });

        if (bestRowIndex != null) {
          const indices = rowGroupsRef.current[bestRowIndex] ?? [];
          setActiveReviewIndices(prev =>
            arraysMatch(prev, indices) ? prev : indices.slice()
          );
        }
      },
      {
        rootMargin: "-12% 0px -48% 0px",
        threshold: [0.25, 0.4, 0.6, 0.8],
      }
    );

    observerRef.current = observer;
    rowGroupsRef.current.forEach((indices, rowIdx) => {
      const node = reviewRefs.current[indices[0]];
      if (node) observer.observe(node);
    });

    return () => {
      observer.disconnect();
      observerRef.current = null;
    };
  }, [spotlightEnabled, rowGroups]);

  useEffect(() => {
    if (!spotlightEnabled) {
      setActiveReviewIndices([]);
      return;
    }
    const firstRow = rowGroups[0] ?? [];
    setActiveReviewIndices(prev =>
      arraysMatch(prev, firstRow) ? prev : firstRow.slice()
    );
  }, [spotlightEnabled, rowGroups]);

  const totalSeconds = 10;
  const progress = done ? 100 : Math.min(100, ((totalSeconds - countdown) / totalSeconds) * 100);
  const buttonRef = useRef<HTMLButtonElement | null>(null);
  const labelRef = useRef<HTMLSpanElement | null>(null);
  const barRef = useRef<HTMLSpanElement | null>(null);

  useEffect(() => {
    let running = true;
    const calc = () => {
      const btn = buttonRef.current;
      const label = labelRef.current;
      const bar = barRef.current;
      if (!btn || !label || !bar) return;
      // Visual feedback calculation removed for simplification
    };
    const loop = () => {
      if (!running) return;
      calc();
      requestAnimationFrame(loop);
    };
    loop();
    window.addEventListener('resize', calc);
    return () => { running = false; window.removeEventListener('resize', calc); };
  }, [done]);

  reviewRefs.current = reviewRefs.current.slice(0, allReviews.length);

  return (
    <div className="min-h-screen bg-white font-nhd text-midnight">
      {/* Main Content */}
		<div className="bg-white text-midnight pb-24 sm:pb-28 md:pb-40 lg:pb-56">{/* extra bottom space for pinned cards */}
			{/* Hero copy at top (visible on all breakpoints) */}
			<section className="pt-6 sm:pt-10">
				<div className="max-w-7xl mx-auto px-4">
					<h1 className="hidden sm:block font-hero font-black text-2xl sm:text-3xl md:text-4xl leading-tight text-center text-midnight">
						{isBusinessHours
							? "We are calling you now from 407-470-1780"
							: "Here's how we transformed the lives of people just like you"
						}
					</h1>
				</div>
			</section>
			{/* Customer Review Images Grid - unified wall */}
			<section className="py-0 lg:py-4 min-h-screen flex items-start lg:items-stretch">
				<div className="w-full px-2 sm:px-4">
					{/* Unified wall of reviews */}
					<div className="reviews-grid grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6 gap-y-0 gap-x-2 sm:gap-x-3 sm:gap-y-0 md:gap-x-4 md:gap-y-0 lg:gap-x-6 lg:gap-y-0">
              {allReviews.map((item, i) => {
                const rowIndex = Math.floor(i / columnCount);
                return (
                  <div
                    key={i}
                    ref={(el) => {
                      reviewRefs.current[i] = el;
                    }}
                    data-row-index={rowIndex}
                    className="relative flex justify-center w-full overflow-visible review-card-wrapper"
                    style={{ zIndex: 200 + (spotlightEnabled && activeReviewIndices.includes(i) ? 1000 : i) }}
                  >
                    <div
                      className={`transition-transform transition-opacity duration-[400ms] ease-out will-change-transform review-card-inner ${
                        spotlightEnabled && activeReviewIndices.includes(i)
                          ? "scale-[1.32] sm:scale-[1.35] opacity-100 drop-shadow-[0_35px_90px_rgba(15,23,42,0.28)]"
                          : "scale-100 opacity-[0.92]"
                      }`}
                    >
                      <Image
                        src={item.src}
                        alt={`Customer review ${i + 1}`}
                        width={640}
                        height={853}
                        sizes="(min-width:1536px) 16vw, (min-width:1280px) 20vw, (min-width:1024px) 22vw, (min-width:768px) 24vw, (min-width:640px) 33vw, 50vw"
                        quality={82}
                        className="w-full h-auto object-contain"
                        priority={spotlightEnabled ? i < 4 : i < 2}
                      />
                    </div>
                  </div>
                );
              })}
					</div>
				</div>
			</section>

      {/* Extra scroll buffer so final rows can reach highlight position */}
      <div aria-hidden className="h-[50vh] sm:h-[40vh] lg:h-[30vh]" />

        {/* Removed testimonials, CTA, and footer per request */}
      </div>

      <style jsx>{`
        @keyframes scrollReviews {
          0% { transform: translateX(0); }
          100% { transform: translateX(-50%); }
        }
        .reviews-grid > * {
          position: relative;
          margin-top: 0;
        }
        .review-card-wrapper {
          transition: opacity 0.35s ease;
        }
        .review-card-inner {
          transform-origin: center;
        }
        .reviews-grid > :nth-child(n + 3) {
          margin-top: -7rem;
        }
        @media (min-width: 640px) {
          .reviews-grid > :nth-child(-n + 3) {
            margin-top: 0;
          }
          .reviews-grid > :nth-child(n + 4) {
            margin-top: -8rem;
          }
        }
        @media (min-width: 768px) {
          .reviews-grid > :nth-child(-n + 4) {
            margin-top: 0;
          }
          .reviews-grid > :nth-child(n + 5) {
            margin-top: -9rem;
          }
        }
        @media (min-width: 1024px) {
          .reviews-grid > :nth-child(-n + 4) {
            margin-top: 0;
          }
          .reviews-grid > :nth-child(n + 5) {
            margin-top: -10rem;
          }
        }
        @media (min-width: 1280px) {
          .reviews-grid > :nth-child(-n + 5) {
            margin-top: 0;
          }
          .reviews-grid > :nth-child(n + 6) {
            margin-top: -11rem;
          }
        }
      `}</style>
      {/* Mobile pinned bottom countdown card */}
      <div className="fixed inset-x-0 bottom-0 z-[9999] md:hidden pointer-events-none">
        <div className="px-3 pb-3">
          <div className="bg-white rounded-3xl shadow-[0_8px_32px_rgba(0,0,0,0.15)] border border-black/5 ring-1 ring-black/5 pointer-events-auto">
            <div className="px-5 pt-4 text-center text-midnight text-[13px] leading-snug font-nhd font-medium">
              Before you get your Free voucher... Check out what people like you had to say!
            </div>
            <div className="p-4 pt-3">
              <button
                ref={buttonRef}
                className={`relative w-full overflow-hidden rounded-full h-12 sm:h-14 px-4 py-0 text-[17px] sm:text-lg font-extrabold tracking-tight transition-colors ${!done ? 'opacity-70 cursor-not-allowed' : 'opacity-100 cursor-pointer'}`}
                style={{ backgroundColor: '#ffffff', border: '1px solid rgba(0,0,0,0.12)' }}
                disabled={!done}
                onClick={() => { if (done) { try { track({ name: 'reviews_move_forward_click', params: { device: 'mobile' } }); } catch {}; router.push('/schedule'); } }}
              >
                <span
                  ref={barRef}
                  className="absolute inset-y-0 left-0 z-10 pointer-events-none bg-sky-300"
                  style={{ width: `${progress}%`, transition: 'width 1s linear' }}
                />
                {/* Dual-label overlay: black base + white clipped to bar width */}
                <span className="absolute inset-0 z-20 pointer-events-none flex items-center justify-center">
                  <span ref={labelRef} className="text-midnight">
                    {done ? 'Move Forward' : countdown}
                  </span>
                  <span
                    className="absolute inset-0 flex items-center justify-center text-white"
                    style={{ clipPath: `inset(0 ${100 - progress}% 0 0)` }}
                  >
                    {done ? 'Move Forward' : countdown}
                  </span>
                </span>
              </button>
            </div>
          </div>
        </div>

        {/* Desktop pinned bottom countdown card via portal */}
        <PinnedCountdownDesktop />
      </div>
    </div>
  );
}
